"""Update AnomalyDetection  model

Revision ID: 919577d35d51
Revises: adfe129b6191
Create Date: 2025-10-25 18:37:49.343171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919577d35d51'
down_revision: Union[str, Sequence[str], None] = 'adfe129b6191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomaly_detections', sa.Column('user_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anomaly_detections', 'user_feedback')
    # ### end Alembic commands ###
