"""Update PeerStatistics model

Revision ID: adfe129b6191
Revises: c8e9ae755983
Create Date: 2025-10-25 15:38:00.283879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfe129b6191'
down_revision: Union[str, Sequence[str], None] = 'c8e9ae755983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('anomaly_detections_user_id_fkey'), 'anomaly_detections', type_='foreignkey')
    op.create_foreign_key(None, 'anomaly_detections', 'user_profiles', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('bill_metrics_bill_id_fkey'), 'bill_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'bill_metrics', 'user_bills', ['bill_id'], ['id'], ondelete='CASCADE')
    op.add_column('peer_statistics', sa.Column('median_consumption_kwh', sa.Float(), nullable=False))
    op.add_column('peer_statistics', sa.Column('percentile_25_kwh', sa.Float(), nullable=False))
    op.add_column('peer_statistics', sa.Column('percentile_75_kwh', sa.Float(), nullable=False))
    op.add_column('peer_statistics', sa.Column('avg_cost_euros', sa.Float(), nullable=True))
    op.add_column('peer_statistics', sa.Column('avg_cost_per_kwh', sa.Float(), nullable=True))
    op.drop_constraint(op.f('user_bills_user_id_fkey'), 'user_bills', type_='foreignkey')
    op.create_foreign_key(None, 'user_bills', 'user_profiles', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_bills', type_='foreignkey')
    op.create_foreign_key(op.f('user_bills_user_id_fkey'), 'user_bills', 'user_profiles', ['user_id'], ['user_id'])
    op.drop_column('peer_statistics', 'avg_cost_per_kwh')
    op.drop_column('peer_statistics', 'avg_cost_euros')
    op.drop_column('peer_statistics', 'percentile_75_kwh')
    op.drop_column('peer_statistics', 'percentile_25_kwh')
    op.drop_column('peer_statistics', 'median_consumption_kwh')
    op.drop_constraint(None, 'bill_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('bill_metrics_bill_id_fkey'), 'bill_metrics', 'user_bills', ['bill_id'], ['id'])
    op.drop_constraint(None, 'anomaly_detections', type_='foreignkey')
    op.create_foreign_key(op.f('anomaly_detections_user_id_fkey'), 'anomaly_detections', 'user_profiles', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
