"""initial

Revision ID: c8e9ae755983
Revises: 
Create Date: 2025-10-21 20:53:22.228091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e9ae755983'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peer_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_size', sa.Integer(), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('avg_consumption_kwh', sa.Float(), nullable=False),
    sa.Column('std_dev_consumption_kwh', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peer_statistics_household_size'), 'peer_statistics', ['household_size'], unique=False)
    op.create_index(op.f('ix_peer_statistics_id'), 'peer_statistics', ['id'], unique=False)
    op.create_index(op.f('ix_peer_statistics_year'), 'peer_statistics', ['year'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.Integer(), nullable=False),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('property_size_sqm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_user_profiles_postal_code'), 'user_profiles', ['postal_code'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_username'), 'user_profiles', ['username'], unique=True)
    op.create_table('weather_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('heating_degree_days', sa.Float(), nullable=False),
    sa.Column('average_temperature_celsius', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_cache_id'), 'weather_cache', ['id'], unique=False)
    op.create_index(op.f('ix_weather_cache_postal_code'), 'weather_cache', ['postal_code'], unique=False)
    op.create_index(op.f('ix_weather_cache_year'), 'weather_cache', ['year'], unique=False)
    op.create_table('user_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bill_year', sa.Integer(), nullable=False),
    sa.Column('bill_year_confidence', sa.Float(), nullable=True),
    sa.Column('consumption_kwh', sa.Float(), nullable=False),
    sa.Column('consumption_kwh_confidence', sa.Float(), nullable=True),
    sa.Column('total_cost_euros', sa.Float(), nullable=False),
    sa.Column('total_cost_euros_confidence', sa.Float(), nullable=True),
    sa.Column('billing_start_date', sa.Date(), nullable=False),
    sa.Column('billing_start_date_confidence', sa.Float(), nullable=True),
    sa.Column('billing_end_date', sa.Date(), nullable=False),
    sa.Column('billing_end_date_confidence', sa.Float(), nullable=True),
    sa.Column('tariff_rate', sa.Float(), nullable=True),
    sa.Column('tariff_rate_confidence', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bills_bill_year'), 'user_bills', ['bill_year'], unique=False)
    op.create_index(op.f('ix_user_bills_id'), 'user_bills', ['id'], unique=False)
    op.create_index(op.f('ix_user_bills_user_id'), 'user_bills', ['user_id'], unique=False)
    op.create_table('anomaly_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('detection_date', sa.DateTime(), nullable=True),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('severity_level', sa.String(length=20), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('historical_score', sa.Float(), nullable=True),
    sa.Column('peer_score', sa.Float(), nullable=True),
    sa.Column('predictive_score', sa.Float(), nullable=True),
    sa.Column('current_consumption_kwh', sa.Float(), nullable=False),
    sa.Column('comparison_value', sa.Float(), nullable=True),
    sa.Column('deviation_percent', sa.Float(), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=False),
    sa.Column('recommendations_text', sa.Text(), nullable=True),
    sa.Column('estimated_extra_cost_euros', sa.Float(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['user_bills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_detections_bill_id'), 'anomaly_detections', ['bill_id'], unique=False)
    op.create_index(op.f('ix_anomaly_detections_id'), 'anomaly_detections', ['id'], unique=False)
    op.create_index(op.f('ix_anomaly_detections_severity_level'), 'anomaly_detections', ['severity_level'], unique=False)
    op.create_index(op.f('ix_anomaly_detections_user_id'), 'anomaly_detections', ['user_id'], unique=False)
    op.create_table('bill_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('days_in_billing_period', sa.Integer(), nullable=False),
    sa.Column('daily_avg_consumption_kwh', sa.Float(), nullable=False),
    sa.Column('cost_per_kwh', sa.Float(), nullable=False),
    sa.Column('yoy_consumption_change_percent', sa.Float(), nullable=True),
    sa.Column('previous_year_consumption_kwh', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['user_bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_metrics_bill_id'), 'bill_metrics', ['bill_id'], unique=True)
    op.create_index(op.f('ix_bill_metrics_id'), 'bill_metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_metrics_id'), table_name='bill_metrics')
    op.drop_index(op.f('ix_bill_metrics_bill_id'), table_name='bill_metrics')
    op.drop_table('bill_metrics')
    op.drop_index(op.f('ix_anomaly_detections_user_id'), table_name='anomaly_detections')
    op.drop_index(op.f('ix_anomaly_detections_severity_level'), table_name='anomaly_detections')
    op.drop_index(op.f('ix_anomaly_detections_id'), table_name='anomaly_detections')
    op.drop_index(op.f('ix_anomaly_detections_bill_id'), table_name='anomaly_detections')
    op.drop_table('anomaly_detections')
    op.drop_index(op.f('ix_user_bills_user_id'), table_name='user_bills')
    op.drop_index(op.f('ix_user_bills_id'), table_name='user_bills')
    op.drop_index(op.f('ix_user_bills_bill_year'), table_name='user_bills')
    op.drop_table('user_bills')
    op.drop_index(op.f('ix_weather_cache_year'), table_name='weather_cache')
    op.drop_index(op.f('ix_weather_cache_postal_code'), table_name='weather_cache')
    op.drop_index(op.f('ix_weather_cache_id'), table_name='weather_cache')
    op.drop_table('weather_cache')
    op.drop_index(op.f('ix_user_profiles_username'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_postal_code'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_peer_statistics_year'), table_name='peer_statistics')
    op.drop_index(op.f('ix_peer_statistics_id'), table_name='peer_statistics')
    op.drop_index(op.f('ix_peer_statistics_household_size'), table_name='peer_statistics')
    op.drop_table('peer_statistics')
    # ### end Alembic commands ###
