"""create invoices table

Revision ID: f80932a07579
Revises: 93d458957a99
Create Date: 2025-10-08 20:22:40.244415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80932a07579'
down_revision: Union[str, Sequence[str], None] = '93d458957a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(), nullable=False),
    sa.Column('supplier_raw', sa.String(), nullable=True),
    sa.Column('supplier_confidence', sa.Float(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('customer_raw', sa.String(), nullable=True),
    sa.Column('customer_confidence', sa.Float(), nullable=True),
    sa.Column('billing_start', sa.Date(), nullable=True),
    sa.Column('billing_end', sa.Date(), nullable=True),
    sa.Column('billing_raw', sa.String(), nullable=True),
    sa.Column('billing_confidence', sa.Float(), nullable=True),
    sa.Column('total_consumption', sa.Float(), nullable=True),
    sa.Column('consumption_raw', sa.String(), nullable=True),
    sa.Column('consumption_confidence', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('amount_raw', sa.String(), nullable=True),
    sa.Column('amount_confidence', sa.Float(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('issue_raw', sa.String(), nullable=True),
    sa.Column('issue_confidence', sa.Float(), nullable=True),
    sa.Column('additional_fields', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
